spring:
  datasource:
   url: jdbc:postgresql://localhost:5432/phoneshop
   username: phoneshop
   password: phoneshop
  jpa:
   properties:
    hibernate: org.hibernate.dialect.PostgreSQLDialect   
   hibernate:
      ddl-auto: update
      
